export const THEMES = {
  cyber: { main: '#00F0FF', text: '#FFFFFF', muted: '#005F66', bg: '#000000' },
  white: { main: '#374151', text: '#000000', muted: '#9CA3AF', bg: '#F3F4F6' },
  black: { main: '#E0E0E0', text: '#FFFFFF', muted: '#333333', bg: '#0A0A0A' }
};

export const LANG_PACK = {
  zh_TW: {
    status: "狀態: ",
    status_ready: "核心組件已就緒",
    parsing: "正在解析影片資訊...",
    parse_success: "解析成功",
    dl_btn: "開始下載",
    preview: "預覽區域",
    placeholder: "請在此處貼上 YouTube 網址...按Enter或點擊右方開始解析鈕....",
    core_ready: "核心就緒",
    mon_label: "監控",
    reset_label: "重置",
    set_label: "設定",
    prog_ready: "準備中...",
    progress: "目前進度: ",
    auto_select: "自動選擇",
    v_quality: "影片品質",
    a_quality: "音訊品質",
    copy_all: "複製", 
    mon_on: "監控模式已開啟：等待下一次複製 YouTube 連結...",
    mon_off: "監控模式已關閉。",
    repairing: "正在嘗試修復核心組件...",
    repair_fail: "修復失敗",
    dl_start: "啟動下載任務...",
    dl_done: "下載任務完成！",
    core_scan: "正在掃描賽博核心組件 (yt-dlp, ffmpeg)...",
    core_ok: "核心組件掃描正常，系統已就緒。",
    core_warn: "[警告] 偵測到核心組件缺失！",
    clip_err: "無法讀取剪貼簿。",
    set_path: "設定儲存路徑",
    user_guide: "使用說明",
    select_folder: "請選擇下載儲存資料夾",
    path_updated: "下載路徑已更新：",
    guide_title: "使用說明",
    guide_content: "1. 在輸入框貼上 YouTube 連結後按下 Enter 鍵或點擊右方 開始解析 鈕開始解析。\n2. 解析成功後，可於下方選單調整影片或音訊下載品質。\n3. 按下右下角顯眼的「開始下載」按鈕啟動任務。\n4. 開啟「監控」，複製網址時系統會自動偵測填入 YouTube 連結並解析。\n5. 本程式支援下載中「中止」下載以及暫停、續傳下載。\n6. 本程式會自動偵測核心組件，若有缺失請按照提示點擊進行下載修復。\n7. 核心組件如有更新訊息建議更新，以免下載失敗。\n8. 本程式可更改下載位置，預設為C:/Users/<你的名稱>/Downloads。 \n9. 下方有文字大小拉桿可做介面文字放大與縮小，左方開關為程式外框(windows系統標題框)的開與關，此外框可自由拉大縮小但不會變動本身程式介面大小(此功能給有更改windows協助工具文字大小的使用者用)，但由於外框背景是透明的如外框點了放大變全螢幕，雖然您看的到桌面但您滑鼠將無法點擊後方任何資料與檔案，請注意!!!!!",
    guide_footer: "歡迎你的使用",
    author_name: "CAIREN_TW", 
    author_title: "作者",
    about_title: "關於本程式",
    support_title: "支持作者",
    about_label: "關於",
    about_menu_item: "關於程式",
    support_menu_item: "贊助作者",
    tech_core: "技術核心",
    disclaimer_title: "免責聲明",
    disclaimer_content: "1. 本程式僅作為技術交流與學術研究之用。\n2. 使用者必須遵守當地法律及相關影音平台的服務條款。\n3. 本程式不存儲、不緩存任何影音檔案，下載受版權保護內容之法律責任由使用者承擔。",
    dev_speech: "嗨！我是開發者。如果你覺得這個工具幫你節省了時間，歡迎請我喝杯咖啡支持！",
    donate_tw: "歐付寶 (台灣)", 
    donate_intl: "PayPal (全球)", 
    donate_btn: "前往贊助",
    thanks_msg: "感謝您的使用與支持",
    path_error: "⚠️ 此資料夾受到系統保護，請選擇『桌面』或『下載』資料夾！",
    default_path_msg: "📁 已自動設定預設下載路徑：下載資料夾",
    label_gui: "使用者介面",
    label_engine: "下載引擎",
    label_runtime: "執行環境",
    label_processor: "後製處理",
    log_extracting: "🔗 正在提取影片網址...",
    log_webpage: "🌐 正在讀取 YouTube 頁面...",
    log_config: "⚙️ 正在取得客戶端配置...",
    log_player: "📦 正在加載播放組件...",
    log_api_tv: "📑 正在取得影片資訊...",
    log_api_android: "📑 正在取得影片資訊...",
    log_format: "📥 準備下載指定格式: ",
    log_merger: "🎬 正在合併影片與音軌...",
    log_extract_audio: "🎵 正在提取音訊並轉檔...",
    log_convertor: "🎥 正在進行格式轉換...",
    log_fixup: "🛠️ 正在修復檔案封裝...",
    // [修正鍵名] 這裡改為 donate_easypay 配合 useVideoApp 的調用
    donate_easypay: "悠遊付 (台灣專用)",
    easy_pay_title: "悠遊付贊助",
    // [2026-01-24 新增] 防災攔截提示文字
    warn_playlist: "💡 偵測到播放清單連結。請貼入單部影片或歌曲連結進行下載。",
    warn_channel: "⚠️ 這是頻道網址，請點入具體影片後再複製網址下載。",
    // [2026-01-26 新增]
    log_resuming: "🔄 偵測到暫存檔，正在恢復續傳...",
    cancel_label: "中止",
    log_canceling: "🛑 正在中止任務並清理暫存檔...",
    log_cancel_done: "✅ 任務已中止，暫存檔已移除。",
    btn_pause: "暫停下載",
    btn_resume: "繼續下載",
    log_pause: "⏸️ 下載已暫停",
    log_resuming_custom: "🚀 偵測到暫存檔，正在執行續傳下載...",
    log_found_existing: "✅ 偵測到本地已存在完整檔案，準備進入後處理...",
    log_resume_connect: "🛰️ 連結已重新建立，繼續搬運格式: ",
    log_merger_detected: "🔍 偵測到已下載軌道，正在跳轉至合併階段...",
    log_ffmpeg_mux: "⚡ 軌道就緒，正在進行最後封裝 (FFmpeg)...",
    log_no_temp_found: "💨 未偵測到有效暫存檔，開始重新下載...",
    log_invalid_url: "⚠️ 無法辨識此網址，請確認網址是否正確。",
    log_analyzing_wait: "⏳ 正在解析中，請稍候...",
    log_analyze_error: "❌ 解析失敗",
  },
  en: {
    status: "Status: ",
    status_ready: "Core components ready",
    parsing: "Parsing video info...",
    parse_success: "Parse successful",
    dl_btn: "DOWNLOAD",
    preview: "PREVIEW",
    placeholder: "Paste YouTube URL here... Press Enter or click Analyze.",
    core_ready: "CORE READY",
    mon_label: "MONITOR",
    reset_label: "RESET",
    set_label: "SETTINGS",
    prog_ready: "Ready...",
    progress: "Progress: ",
    auto_select: "Auto selection",
    v_quality: "VIDEO",
    a_quality: "AUDIO",
    copy_all: "Copy", 
    mon_on: "Monitor Active: Waiting for YouTube link in clipboard...",
    mon_off: "Monitor OFF.",
    repairing: "Attempting to repair core components...",
    repair_fail: "Repair failed",
    dl_start: "Starting download task...",
    dl_done: "Download task completed!",
    core_scan: "Scanning cyber core (yt-dlp, ffmpeg)...",
    core_ok: "Core components scan normal. System ready.",
    core_warn: "[WARNING] Core components missing!",
    clip_err: "Clipboard access denied.",
    set_path: "Change Download Location",
    user_guide: "User Guide",
    select_folder: "Select Download Folder",
    path_updated: "Path Updated: ",
    guide_title: "User Guide",
    guide_content: "1. Paste YouTube URL here... Press Enter or click Analyze.\n2. Once analyzed, adjust video or audio quality from the dropdown menus.\n3. Click the prominent 'DOWNLOAD' button to start the task.\n4. Enable 'Monitor' to automatically detect and fill in YouTube links when you copy them to your clipboard.\n5. The app supports canceling, pausing, and resuming downloads.\n6. Core components are scanned automatically. If any are missing, follow the prompts to repair them.\n7. It is recommended to update core components when prompted to ensure download stability.\n8. The default download path is your system Downloads folder; you can change this in settings.\n9. Use the slider at the bottom to adjust text size. The left switch toggles the Windows system title bar. Note: While the window can be resized or maximized, the interface stays fixed. Because the extended background is transparent, maximizing the window may block mouse clicks on your desktop. Please use with caution!",
    author_name: "CAIREN_TW", 
    author_title: "Author",
    about_title: "About Application",
    support_title: "Support Author",
    about_label: "About ",
    about_menu_item: "About",
    support_menu_item: "Support",
    tech_core: "Technical Core",
    disclaimer_title: "Disclaimer",
    disclaimer_content: "1. This tool is for educational and research purposes only.\n2. Users must comply with local laws and platform terms of service.\n3. This app does not store media files; users are responsible for the legal consequences of their downloads.",
    dev_speech: "Hi! I'm the developer. If this tool saved you time, feel free to buy me a coffee! Any support is greatly appreciated.",
    donate_tw: "O'Pay (Taiwan)", 
    donate_intl: "PayPal (Global)", 
    donate_btn: "Go to Donate",
    thanks_msg: "Thank you for your support",
    path_error: "⚠️ Folder protected by system. Please choose 'Desktop' or 'Downloads'!",
    default_path_msg: "📁 Default path set to Downloads folder",
    label_gui: "GUI",
    label_engine: "Engine",
    label_runtime: "Runtime",
    label_processor: "Processor",
    log_extracting: "🔗 Extracting URL...",
    log_webpage: "🌐 Downloading webpage...",
    log_config: "⚙️ Downloading client config...",
    log_player: "📦 Loading player components...",
    log_api_tv: "📑 Fetching video metadata...",
    log_api_android: "📑 Fetching video metadata...",
    log_format: "📥 Preparing format: ",
    log_merger: "🎬 Merging video and audio tracks...",
    log_extract_audio: "🎵 Extracting and converting audio...",
    log_convertor: "🎥 Converting video format...",
    log_fixup: "🛠️ Fixing file encapsulation...",
    // [修正鍵名] 這裡改為 donate_easypay 配合 useVideoApp 的調用
    donate_easypay: "Easy Wallet (Taiwan Only)",
    easy_pay_title: "Easy Wallet Support",
    // [2026-01-24 新增] Anti-crash interception text
    warn_playlist: "💡 Playlist detected. Please paste a single video or song link.",
    warn_channel: "⚠️ This is a channel link. Please select a specific video to download.",
    // [2026-01-26 新增]
    log_resuming: "🔄 Resuming from cache, continuing download...",
    cancel_label: "Cancel",
    log_canceling: "🛑 Canceling task and cleaning up temp files...",
    log_cancel_done: "✅ Task canceled and temp files removed.",
    btn_pause: "PAUSE",
    btn_resume: "RESUME",
    log_pause: "⏸️ Download Paused",
    log_resuming_custom: "🚀 Cache detected, resuming download task...",
    log_found_existing: "✅ Complete file found, finalizing...",
    log_resume_connect: "🛰️ Reconnected, continuing format: ",
    log_merger_detected: "🔍 Tracks detected, skipping to merge stage...",
    log_ffmpeg_mux: "⚡ Tracks ready, performing final muxing (FFmpeg)...",
    log_no_temp_found: "💨 No valid temporary archive file detected. Re-downloading the file…",
    log_invalid_url: "⚠️ Invalid URL. Please check your link.",
    log_analyzing_wait: "⏳ Analyzing, please wait...",
    log_analyze_error: "❌ Analysis failed",
  }
};